<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DiagnosticExplorer.Serilog</AssemblyName>
    <RootNamespace>DiagnosticExplorer.Serilog</RootNamespace>
    <IsDiagnosticExplorerPackage>true</IsDiagnosticExplorerPackage>
    <Version>$(DiagnosticExplorerPackageVersion)</Version>
    <AssemblyVersion>$(DiagnosticExplorerAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(DiagnosticExplorerFileVersion)</FileVersion>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Serilog sink for DiagnosticExplorer.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiagnosticExplorer\DiagnosticExplorer.csproj" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

</Project>