<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DiagnosticExplorer.Serilog</AssemblyName>
    <RootNamespace>DiagnosticExplorer.Serilog</RootNamespace>
    <Version>3.1.38</Version>
    <AssemblyVersion>3.1.38.0</AssemblyVersion>
    <FileVersion>3.1.38.0</FileVersion>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Serilog sink for DiagnosticExplorer.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiagnosticExplorer\DiagnosticExplorer.csproj" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

</Project>