<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DiagnosticExplorer.NLog</AssemblyName>
    <RootNamespace>DiagnosticExplorer.NLog</RootNamespace>
    <IsDiagnosticExplorerPackage>true</IsDiagnosticExplorerPackage>
    <Version>$(DiagnosticExplorerPackageVersion)</Version>
    <AssemblyVersion>$(DiagnosticExplorerAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(DiagnosticExplorerFileVersion)</FileVersion>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>NLog target for DiagnosticExplorer.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiagnosticExplorer\DiagnosticExplorer.csproj" />
    <PackageReference Include="NLog" Version="5.4.0" />
  </ItemGroup>

</Project>