<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DiagnosticExplorer.NLog</AssemblyName>
    <RootNamespace>DiagnosticExplorer.NLog</RootNamespace>
    <Version>3.1.38</Version>
    <AssemblyVersion>3.1.38.0</AssemblyVersion>
    <FileVersion>3.1.38.0</FileVersion>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>NLog target for DiagnosticExplorer.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiagnosticExplorer\DiagnosticExplorer.csproj" />
    <PackageReference Include="NLog" Version="5.4.0" />
  </ItemGroup>

</Project>