<Project>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)DiagnosticsConfiguration.cs" Link="Harness\DiagnosticsConfiguration.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)Form1.cs" Link="Harness\Form1.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)Form1.Designer.cs" Link="Harness\Form1.Designer.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)Gadget.cs" Link="Harness\Gadget.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)GadgetConfig.cs" Link="Harness\GadgetConfig.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)SampleLogLevel.cs" Link="Harness\SampleLogLevel.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)TraceScopeExample.cs" Link="Harness\TraceScopeExample.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)Widget.cs" Link="Harness\Widget.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)Thing.cs" Link="Harness\Thing.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)WidgetConfig.cs" Link="Harness\WidgetConfig.cs" />
    <EmbeddedResource Include="$(MSBuildThisFileDirectory)Form1.resx" Link="Harness\Form1.resx" />
    <None Remove="$(MSBuildThisFileDirectory)config.json" Link="config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>